### PR TITLE
Updating Header Image

### PR DESCRIPTION
**Pull request by ashwani-rathee**
Added the header similar to the design created by @cormullion

Few things to mention 
- I didn't make a separate css file,I can do that if it's necessary,though it's just two blocks of CSS
- this header will appear in all the pages ,that could be problem. if you don't want that,I can update that too..
- It is in center of the page,which kind of makes it look ugly(actually it doesn't look symmetric,the one designed by @cormullion kind of aligns with the options starting from left..)
- Color is different from the one used by @cormullion in background..
- [x] included the header sketch

### CODE REVIEW

**Comment by ashwani-rathee** [comment]
It definitely would be,I should do that for both CSS,SVG then :) makes it all cleaner

**Comment by cormullion** [comment]
On reflection I'd dial the blue down a bit more - it wasn't really necessary in the first place, more of a hint of a page edge than anything else - and that would make the purple color a bit less murky  too. But you should go with what looks right to you.

**Comment by ashwani-rathee** [comment]
@cormullion pls suggest a color for that fade effect,I coudn't really find the right one https://www.color-hex.com/color/0000ff

**Comment by cormullion** [comment]
I can make you a wider design too. How many pixels?

**Comment by ashwani-rathee** [comment]
@cormullion @ChrisRackauckas I was actually thinking of a completely redesign of the website,The current site was just to transfer all the old data to the new one....I am thinking of the design and how it could look best and discuss with the team..like to have proper navigation bar(not the sketch)... then the sketch as whole below the navigation bar 
something similiar to this

PkgPage.jl by @tlienart  is made to do just that..
https://www.desmos.com/ is pretty good 
https://www.wolframalpha.com/ is okay

**Comment by ChrisRackauckas** [comment]
I do like banners at the top like that, and I think you showed one with a cool animation before?

**Comment by ashwani-rathee** [comment]
We could do that,we will have to make a gif of that animation...I remember you saying it would be cool if the animation was made using SCIML,I don't have the skills to make a good animation:/
Then @cormullion can design the sketch according the site contrast colors of background and the animation being dispersing in the same color as background ,make it part of the website not just a box..

**Pull request merged**
