### PR TITLE
files for _site folder

### PR DESCRIPTION
**Pull request by ashwani-rathee**
-continuation of jekyll to franklin

### CODE REVIEW

**Comment by ViralBShah** [comment]
Should we just merge this to get a site up and running?

**Comment by ashwani-rathee** [comment]
These _site files are like they combine the the whole franklin scripts to proper HTML form..so yeah they need to be merged..

**Comment by ChrisRackauckas** [comment]
yes

**Comment by ashwani-rathee** [comment]
Has it been deployed ?? https://franklinjl.org/workflow/deploy/ can be used for to deploy

**Comment by ashwani-rathee** [comment]
https://silly-wilson-497eb3.netlify.app/ 
deployed on netlify from my fork for preview,github pages are acting little funny-will be deployed there too by evening

**Comment by ViralBShah** [comment]
Thanks for getting this up so quickly! I will start taking a deeper look.

**Pull request merged**
